### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Diego-Pino** [Darkensses/sofifa-pyscraper#1]
Hola.
para reportar este error, nunca me habia pasado pero igual lo traigo por si alguna otra persona tiene el mismo error

> Traceback (most recent call last):
> File "main.py", line 110, in <module>
> "name_league": re.sub("(\s)(\\xa0)?(\(\d\))", "", Selector(league).xpath("//text()").get())}
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/re.py", line 208, in sub
> TypeError: expected string or bytes-like object

![python](https://i.ibb.co/0sPjZ1S/pyscraper.png)

-

**Comment by Darkensses** [comment]
Probablemnte sea porque han cambiando el xpath de ese elemnto. En investigación

**Comment by Darkensses** [comment]
Arreglado
